In [1]:
#importamos a panda
import pandas as pd
import numpy as np

In [2]:
#descargamos los datos
df=pd.read_csv('aguaprieta2',skiprows=20,skipfooter=1, sep='\s+',header=None,
               names=['DD/MM/YY','PRECIP','EVAP','TMAX','TMIN'],engine='python')

In [4]:
df.dtypes

DD/MM/YY     object
PRECIP      float64
EVAP        float64
TMAX        float64
TMIN        float64
dtype: object

In [5]:
df['FECHA'] = pd.to_datetime(df.apply(lambda x: x['DD/MM/YY'], 1), dayfirst=True)
df=df.drop(['DD/MM/YY'],1)

In [6]:
df.dtypes

PRECIP           float64
EVAP             float64
TMAX             float64
TMIN             float64
FECHA     datetime64[ns]
dtype: object

In [7]:
df.head()

   PRECIP  EVAP  TMAX  TMIN      FECHA
0     0.0   NaN  19.5   2.0 1961-02-01
1     0.0   NaN  20.0   2.5 1961-02-02
2     0.0   2.7  21.5   1.8 1961-02-03
3     0.0   3.0  16.7   1.0 1961-02-04
4     0.0   1.3  11.4   4.0 1961-02-05

In [8]:
df.tail()

       PRECIP  EVAP  TMAX  TMIN      FECHA
16747     0.0   6.4  36.0  20.0 2011-07-27
16748    13.0   6.2  37.0  20.0 2011-07-28
16749     0.0   4.2  36.0  20.0 2011-07-29
16750    11.0   1.7  35.0  20.0 2011-07-30
16751    13.0   NaN  34.0  21.0 2011-07-31

In [9]:
df.mean()

PRECIP     0.955698
EVAP       5.679653
TMAX      26.371555
TMIN       8.596580
dtype: float64

In [10]:
df.std()

PRECIP    4.043399
EVAP      3.137320
TMAX      8.018800
TMIN      7.895741
dtype: float64

In [11]:
df.median()

PRECIP     0.0
EVAP       5.3
TMAX      27.0
TMIN       8.0
dtype: float64

In [12]:
df.max()

PRECIP                     70
EVAP                     17.6
TMAX                       45
TMIN                       27
FECHA     2011-07-31 00:00:00
dtype: object

In [13]:
df.min()

PRECIP                      0
EVAP                        0
TMAX                     -3.5
TMIN                    -19.5
FECHA     1961-02-01 00:00:00
dtype: object

In [14]:
df.describe()

             PRECIP          EVAP          TMAX          TMIN
count  16733.000000  12277.000000  16446.000000  16435.000000
mean       0.955698      5.679653     26.371555      8.596580
std        4.043399      3.137320      8.018800      7.895741
min        0.000000      0.000000     -3.500000    -19.500000
25%        0.000000      3.100000     20.000000      2.000000
50%        0.000000      5.300000     27.000000      8.000000
75%        0.000000      7.900000     33.000000     16.000000
max       70.000000     17.600000     45.000000     27.000000

In [15]:
df['MES'] = df['FECHA'].dt.month

In [16]:
df['AÑO']=df['FECHA'].dt.year

In [17]:
df.head()

   PRECIP  EVAP  TMAX  TMIN      FECHA  MES   AÑO
0     0.0   NaN  19.5   2.0 1961-02-01    2  1961
1     0.0   NaN  20.0   2.5 1961-02-02    2  1961
2     0.0   2.7  21.5   1.8 1961-02-03    2  1961
3     0.0   3.0  16.7   1.0 1961-02-04    2  1961
4     0.0   1.3  11.4   4.0 1961-02-05    2  1961

In [18]:
pd.options.display.max_rows=10000

In [20]:
#aqui hacemos un for loop donde segun el mes nos da la suma
for i in range(1,13):
        PRECIPMENS =  df.loc[df['MES'] == i, 'PRECIP'].sum()
        print('MES',i,np.round(PRECIPMENS,decimals=1),'mm')

MES 1 893.9 mm
MES 2 786.0 mm
MES 3 486.4 mm
MES 4 291.3 mm
MES 5 245.3 mm
MES 6 550.6 mm
MES 7 4116.4 mm
MES 8 3499.4 mm
MES 9 1870.7 mm
MES 10 1083.3 mm
MES 11 873.8 mm
MES 12 1294.6 mm

In [21]:
#esto es para sumar los datos de una columna donde cumple con la condicion de otra columna
df.loc[df['MES'] == 2, 'PRECIP'].sum()

786.0

In [22]:
#aqui hacemos un for loop donde segun el mes nos da la suma
for i in range(1,13):
        TMINMENS =  df.loc[df['MES'] == i, 'TMIN'].min()
        print('MES',i,np.round(TMINMENS,decimals=1),'C')

MES 1 -12.5 C
MES 2 -12.0 C
MES 3 -9.0 C
MES 4 -3.5 C
MES 5 -1.0 C
MES 6 2.1 C
MES 7 2.0 C
MES 8 10.0 C
MES 9 2.0 C
MES 10 -4.0 C
MES 11 -8.5 C
MES 12 -19.5 C

In [23]:
#aqui hacemos un for loop donde segun el mes nos da la suma
for i in range(1,13):
        TMAXMENS =  df.loc[df['MES'] == i, 'TMAX'].max()
        print('MES',i,np.round(TMAXMENS,decimals=1),'C')

MES 1 30.0 C
MES 2 32.0 C
MES 3 35.0 C
MES 4 38.0 C
MES 5 42.0 C
MES 6 45.0 C
MES 7 44.0 C
MES 8 42.0 C
MES 9 41.0 C
MES 10 38.0 C
MES 11 36.0 C
MES 12 31.0 C

In [24]:
#aqui hacemos un for loop donde segun el mes nos da la suma
for i in range(1961,2012):
        EVAPAÑO =  df.loc[df['AÑO'] == i, 'EVAP'].sum()
        print('AÑO',i,np.round(EVAPAÑO,decimals=1),'')

AÑO 1961 1980.9
AÑO 1962 1303.9
AÑO 1963 484.2
AÑO 1964 2062.6
AÑO 1965 2094.6
AÑO 1966 2080.2
AÑO 1967 2183.6
AÑO 1968 2018.4
AÑO 1969 2062.2
AÑO 1970 1864.9
AÑO 1971 1893.9
AÑO 1972 51.5
AÑO 1973 92.7
AÑO 1974 2315.1
AÑO 1975 2400.5
AÑO 1976 2189.7
AÑO 1977 2183.6
AÑO 1978 2248.2
AÑO 1979 2382.7
AÑO 1980 2433.5
AÑO 1981 2247.8
AÑO 1982 2156.0
AÑO 1983 2093.1
AÑO 1984 1087.1
AÑO 1985 0.0
AÑO 1986 0.0
AÑO 1987 20.3
AÑO 1988 0.0
AÑO 1989 0.0
AÑO 1990 0.0
AÑO 1991 0.0
AÑO 1992 0.0
AÑO 1993 0.0
AÑO 1994 2014.2
AÑO 1995 2089.4
AÑO 1996 2201.7
AÑO 1997 2076.5
AÑO 1998 1724.5
AÑO 1999 0.0
AÑO 2000 223.0
AÑO 2001 0.0
AÑO 2002 1336.8
AÑO 2003 1699.1
AÑO 2004 1629.2
AÑO 2005 1667.7
AÑO 2006 1797.3
AÑO 2007 1662.7
AÑO 2008 1649.9
AÑO 2009 1381.5
AÑO 2010 1425.3
AÑO 2011 1219.1

In [25]:
lista = df['AÑO'].unique()

In [26]:
lista

array([1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982,
       1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993,
       1994, 1995, 1996, 1997, 1998, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011], dtype=int64)

In [27]:
for j in lista:
    for i in range(10,13):
        waza=df.loc[(df['MES']== i) & (df['AÑO']== j),'TMIN'].mean()
        print(j,i,waza)

1961 10 7.403225806451614
1961 11 1.8866666666666663
1961 12 0.3193548387096775
1962 10 nan
1962 11 nan
1962 12 nan
1963 10 9.790322580645162
1963 11 3.1166666666666667
1963 12 -2.2096774193548385
1964 10 8.64516129032258
1964 11 1.95
1964 12 -1.064516129032258
1965 10 6.419354838709677
1965 11 3.8
1965 12 -0.04838709677419355
1966 10 6.741935483870968
1966 11 3.0833333333333335
1966 12 -3.2580645161290325
1967 10 7.790322580645161
1967 11 2.283333333333333
1967 12 -0.6612903225806451
1968 10 6.161290322580645
1968 11 1.0666666666666667
1968 12 -5.032258064516129
1969 10 7.583333333333333
1969 11 0.4666666666666667
1969 12 -2.693548387096774
1970 10 5.290322580645161
1970 11 1.5833333333333333
1970 12 -0.46774193548387094
1971 10 7.82258064516129
1971 11 1.3166666666666667
1971 12 -1.6935483870967742
1972 10 nan
1972 11 nan
1972 12 nan
1973 10 10.774193548387096
1973 11 1.8833333333333333
1973 12 -2.661290322580645
1974 10 10.096774193548388
1974 11 1.95
1974 12 -2.6451612903225805
1975 10 7.161290322580645
1975 11 0.6166666666666667
1975 12 -2.032258064516129
1976 10 7.306451612903226
1976 11 1.6833333333333333
1976 12 -2.0483870967741935
1977 10 10.290322580645162
1977 11 2.433333333333333
1977 12 0.3548387096774194
1978 10 9.080645161290322
1978 11 3.283333333333333
1978 12 -2.1129032258064515
1979 10 7.967741935483871
1979 11 -0.43333333333333335
1979 12 -2.7903225806451615
1980 10 7.32258064516129
1980 11 1.1833333333333333
1980 12 -0.27419354838709675
1981 10 9.564516129032258
1981 11 2.4
1981 12 -0.4838709677419355
1982 10 6.661290322580645
1982 11 3.3333333333333335
1982 12 -1.7741935483870968
1983 10 10.241935483870968
1983 11 3.05
1983 12 0.20967741935483872
1984 10 9.209677419354838
1984 11 3.1666666666666665
1984 12 1.4516129032258065
1985 10 9.0
1985 11 3.3666666666666667
1985 12 -0.08620689655172414
1986 10 8.161290322580646
1986 11 3.65
1986 12 -0.14516129032258066
1987 10 11.596774193548388
1987 11 2.533333333333333
1987 12 -0.45161290322580644
1988 10 10.758064516129032
1988 11 3.1
1988 12 -1.125
1989 10 9.03225806451613
1989 11 3.4166666666666665
1989 12 -1.4516129032258065
1990 10 8.64516129032258
1990 11 4.7
1990 12 0.7741935483870968
1991 10 9.451612903225806
1991 11 3.2
1991 12 1.467741935483871
1992 10 9.451612903225806
1992 11 1.3166666666666667
1992 12 1.3064516129032258
1993 10 9.387096774193548
1993 11 3.0344827586206895
1993 12 0.7903225806451613
1994 10 9.483870967741936
1994 11 3.816666666666667
1994 12 1.935483870967742
1995 10 9.370967741935484
1995 11 5.183333333333334
1995 12 0.43548387096774194
1996 10 8.887096774193548
1996 11 3.8333333333333335
1996 12 0.12903225806451613
1997 10 9.403225806451612
1997 11 4.233333333333333
1997 12 -0.3225806451612903
1998 10 9.058823529411764
1998 11 nan
1998 12 nan
2000 10 10.46774193548387
2000 11 0.13333333333333333
2000 12 -1.3548387096774193
2001 10 10.120689655172415
2001 11 4.266666666666667
2001 12 -3.0161290322580645
2002 10 10.064516129032258
2002 11 4.033333333333333
2002 12 0.8870967741935484
2003 10 12.5
2003 11 5.683333333333334
2003 12 -0.5344827586206896
2004 10 11.14516129032258
2004 11 3.3333333333333335
2004 12 1.103448275862069
2005 10 10.403225806451612
2005 11 4.516666666666667
2005 12 1.032258064516129
2006 10 10.516129032258064
2006 11 4.733333333333333
2006 12 -0.12903225806451613
2007 10 10.03225806451613
2007 11 6.433333333333334
2007 12 0.27586206896551724
2008 10 8.419354838709678
2008 11 5.866666666666666
2008 12 3.0
2009 10 9.772727272727273
2009 11 4.25
2009 12 1.5416666666666667
2010 10 11.8
2010 11 1.7
2010 12 1.391304347826087
2011 10 nan
2011 11 nan
2011 12 nan

In [30]:
for j in lista:
    for i in range(10,13):
        waza=df.loc[(df['MES']== i) & (df['AÑO']== j),'TMAX'].mean()
        print(j,i,waza)

1961 10 28.393548387096764
1961 11 19.256666666666668
1961 12 16.55483870967742
1962 10 nan
1962 11 nan
1962 12 nan
1963 10 29.032258064516128
1963 11 20.016666666666666
1963 12 16.741935483870968
1964 10 27.967741935483872
1964 11 20.466666666666665
1964 12 17.887096774193548
1965 10 29.225806451612904
1965 11 23.683333333333334
1965 12 15.46774193548387
1966 10 27.612903225806452
1966 11 23.05
1966 12 17.516129032258064
1967 10 29.258064516129032
1967 11 23.1
1967 12 13.483870967741936
1968 10 29.903225806451612
1968 11 22.133333333333333
1968 12 17.258064516129032
1969 10 27.758064516129032
1969 11 19.06
1969 12 15.661290322580646
1970 10 29.112903225806452
1970 11 28.266666666666666
1970 12 20.838709677419356
1971 10 22.451612903225808
1971 11 20.716666666666665
1971 12 14.435483870967742
1972 10 nan
1972 11 nan
1972 12 nan
1973 10 26.774193548387096
1973 11 23.35
1973 12 20.20967741935484
1974 10 24.903225806451612
1974 11 21.45
1974 12 15.225806451612904
1975 10 27.193548387096776
1975 11 22.366666666666667
1975 12 17.629032258064516
1976 10 23.419354838709676
1976 11 19.95
1976 12 16.370967741935484
1977 10 25.741935483870968
1977 11 21.016666666666666
1977 12 18.870967741935484
1978 10 27.919354838709676
1978 11 20.516666666666666
1978 12 12.758064516129032
1979 10 29.20967741935484
1979 11 18.833333333333332
1979 12 17.467741935483872
1980 10 25.43548387096774
1980 11 19.933333333333334
1980 12 19.29032258064516
1981 10 24.93548387096774
1981 11 22.716666666666665
1981 12 19.016129032258064
1982 10 27.20967741935484
1982 11 18.133333333333333
1982 12 12.838709677419354
1983 10 23.951612903225808
1983 11 18.266666666666666
1983 12 16.903225806451612
1984 10 22.5
1984 11 18.383333333333333
1984 12 14.112903225806452
1985 10 23.806451612903224
1985 11 19.166666666666668
1985 12 16.413793103448278
1986 10 24.387096774193548
1986 11 18.066666666666666
1986 12 14.17741935483871
1987 10 28.548387096774192
1987 11 19.7
1987 12 14.887096774193548
1988 10 26.596774193548388
1988 11 20.433333333333334
1988 12 16.0
1989 10 27.06451612903226
1989 11 22.0
1989 12 16.677419354838708
1990 10 27.06451612903226
1990 11 20.366666666666667
1990 12 14.35483870967742
1991 10 28.677419354838708
1991 11 20.266666666666666
1991 12 14.064516129032258
1992 10 28.596774193548388
1992 11 18.883333333333333
1992 12 14.516129032258064
1993 10 26.774193548387096
1993 11 19.93103448275862
1993 12 16.451612903225808
1994 10 25.85483870967742
1994 11 18.983333333333334
1994 12 14.35483870967742
1995 10 29.580645161290324
1995 11 23.333333333333332
1995 12 18.016129032258064
1996 10 26.93548387096774
1996 11 22.033333333333335
1996 12 19.129032258064516
1997 10 27.096774193548388
1997 11 21.4
1997 12 12.080645161290322
1998 10 26.305555555555557
1998 11 nan
1998 12 nan
2000 10 24.629032258064516
2000 11 17.566666666666666
2000 12 19.5
2001 10 30.310344827586206
2001 11 22.766666666666666
2001 12 17.06451612903226
2002 10 26.43548387096774
2002 11 23.333333333333332
2002 12 16.5
2003 10 31.451612903225808
2003 11 23.55
2003 12 20.5
2004 10 28.032258064516128
2004 11 21.2
2004 12 18.879310344827587
2005 10 31.774193548387096
2005 11 27.533333333333335
2005 12 24.322580645161292
2006 10 28.258064516129032
2006 11 26.616666666666667
2006 12 20.580645161290324
2007 10 33.193548387096776
2007 11 28.433333333333334
2007 12 19.2
2008 10 32.903225806451616
2008 11 27.3
2008 12 20.63157894736842
2009 10 27.571428571428573
2009 11 26.285714285714285
2009 12 18.083333333333332
2010 10 29.9
2010 11 23.0
2010 12 22.5
2011 10 nan
2011 11 nan
2011 12 nan

In [31]:
for j in lista:
    for i in range(1,13):
        waza=df.loc[(df['MES']== i) & (df['AÑO']== j),'TMAX'].mean()
        print(j,i,waza)

1961 1 nan
1961 2 20.314285714285713
1961 3 23.748387096774195
1961 4 29.646666666666665
1961 5 33.883870967741935
1961 6 38.45666666666667
1961 7 36.735483870967734
1961 8 34.380645161290325
1961 9 32.39999999999999
1961 10 28.393548387096764
1961 11 19.256666666666668
1961 12 16.55483870967742
1962 1 15.738709677419354
1962 2 22.03928571428571
1962 3 20.403225806451612
1962 4 31.136666666666663
1962 5 33.33870967741935
1962 6 37.06333333333334
1962 7 35.87096774193548
1962 8 nan
1962 9 nan
1962 10 nan
1962 11 nan
1962 12 nan
1963 1 nan
1963 2 nan
1963 3 nan
1963 4 nan
1963 5 nan
1963 6 nan
1963 7 nan
1963 8 nan
1963 9 33.43793103448276
1963 10 29.032258064516128
1963 11 20.016666666666666
1963 12 16.741935483870968
1964 1 15.403225806451612
1964 2 16.379310344827587
1964 3 20.467741935483872
1964 4 25.916666666666668
1964 5 32.903225806451616
1964 6 35.9
1964 7 37.435483870967744
1964 8 33.49032258064516
1964 9 31.03333333333334
1964 10 27.967741935483872
1964 11 20.466666666666665
1964 12 17.887096774193548
1965 1 18.532258064516128
1965 2 17.142857142857142
1965 3 20.758064516129032
1965 4 27.05
1965 5 30.5
1965 6 33.95
1965 7 36.04838709677419
1965 8 35.435483870967744
1965 9 31.433333333333334
1965 10 29.225806451612904
1965 11 23.683333333333334
1965 12 15.46774193548387
1966 1 14.774193548387096
1966 2 15.625
1966 3 23.838709677419356
1966 4 27.433333333333334
1966 5 32.33870967741935
1966 6 36.46666666666667
1966 7 37.170967741935485
1966 8 33.00645161290323
1966 9 30.83
1966 10 27.612903225806452
1966 11 23.05
1966 12 17.516129032258064
1967 1 18.56451612903226
1967 2 20.267857142857142
1967 3 25.629032258064516
1967 4 27.366666666666667
1967 5 30.967741935483872
1967 6 35.18333333333333
1967 7 35.403225806451616
1967 8 33.62903225806452
1967 9 31.566666666666666
1967 10 29.258064516129032
1967 11 23.1
1967 12 13.483870967741936
1968 1 16.35483870967742
1968 2 19.637931034482758
1968 3 20.032258064516128
1968 4 24.383333333333333
1968 5 31.096774193548388
1968 6 36.81666666666667
1968 7 34.37096774193548
1968 8 32.17741935483871
1968 9 32.75
1968 10 29.903225806451612
1968 11 22.133333333333333
1968 12 17.258064516129032
1969 1 19.14516129032258
1969 2 18.535714285714285
1969 3 23.548387096774192
1969 4 29.266666666666666
1969 5 32.16129032258065
1969 6 38.28333333333333
1969 7 35.95161290322581
1969 8 36.54838709677419
1969 9 33.0
1969 10 27.758064516129032
1969 11 19.06
1969 12 15.661290322580646
1970 1 17.774193548387096
1970 2 18.928571428571427
1970 3 18.274193548387096
1970 4 25.083333333333332
1970 5 30.64516129032258
1970 6 35.21666666666667
1970 7 36.95161290322581
1970 8 34.61290322580645
1970 9 32.15
1970 10 29.112903225806452
1970 11 28.266666666666666
1970 12 20.838709677419356
1971 1 22.41290322580645
1971 2 20.821428571428573
1971 3 26.096774193548388
1971 4 25.883333333333333
1971 5 29.14516129032258
1971 6 32.31666666666667
1971 7 35.37096774193548
1971 8 32.33870967741935
1971 9 32.81666666666667
1971 10 22.451612903225808
1971 11 20.716666666666665
1971 12 14.435483870967742
1972 1 17.080645161290324
1972 2 16.5
1972 3 21.580645161290324
1972 4 27.033333333333335
1972 5 27.35483870967742
1972 6 31.783333333333335
1972 7 nan
1972 8 nan
1972 9 nan
1972 10 nan
1972 11 nan
1972 12 nan
1973 1 nan
1973 2 nan
1973 3 nan
1973 4 nan
1973 5 nan
1973 6 nan
1973 7 nan
1973 8 nan
1973 9 nan
1973 10 26.774193548387096
1973 11 23.35
1973 12 20.20967741935484
1974 1 13.935483870967742
1974 2 15.728571428571428
1974 3 21.838709677419356
1974 4 25.433333333333334
1974 5 30.661290322580644
1974 6 37.11666666666667
1974 7 33.38709677419355
1974 8 32.645161290322584
1974 9 30.283333333333335
1974 10 24.903225806451612
1974 11 21.45
1974 12 15.225806451612904
1975 1 16.580645161290324
1975 2 18.214285714285715
1975 3 19.758064516129032
1975 4 21.833333333333332
1975 5 27.903225806451612
1975 6 33.88333333333333
1975 7 32.61290322580645
1975 8 35.0
1975 9 30.3
1975 10 27.193548387096776
1975 11 22.366666666666667
1975 12 17.629032258064516
1976 1 17.0
1976 2 20.29310344827586
1976 3 22.5
1976 4 24.066666666666666
1976 5 29.596774193548388
1976 6 35.166666666666664
1976 7 32.37096774193548
1976 8 34.61290322580645
1976 9 29.55
1976 10 23.419354838709676
1976 11 19.95
1976 12 16.370967741935484
1977 1 14.580645161290322
1977 2 19.375
1977 3 18.080645161290324
1977 4 24.483333333333334
1977 5 27.548387096774192
1977 6 34.5
1977 7 33.58064516129032
1977 8 33.70967741935484
1977 9 31.45
1977 10 25.741935483870968
1977 11 21.016666666666666
1977 12 18.870967741935484
1978 1 15.14516129032258
1978 2 15.625
1978 3 21.241935483870968
1978 4 24.85
1978 5 28.983870967741936
1978 6 35.63333333333333
1978 7 36.25806451612903
1978 8 33.03225806451613
1978 9 30.433333333333334
1978 10 27.919354838709676
1978 11 20.516666666666666
1978 12 12.758064516129032
1979 1 11.548387096774194
1979 2 17.928571428571427
1979 3 20.096774193548388
1979 4 25.216666666666665
1979 5 27.225806451612904
1979 6 33.71666666666667
1979 7 35.25806451612903
1979 8 32.064516129032256
1979 9 32.81666666666667
1979 10 29.20967741935484
1979 11 18.833333333333332
1979 12 17.467741935483872
1980 1 16.741935483870968
1980 2 17.46896551724138
1980 3 19.129032258064516
1980 4 24.316666666666666
1980 5 27.838709677419356
1980 6 37.13333333333333
1980 7 36.016129032258064
1980 8 33.03225806451613
1980 9 32.25
1980 10 25.43548387096774
1980 11 19.933333333333334
1980 12 19.29032258064516
1981 1 15.306451612903226
1981 2 19.071428571428573
1981 3 18.580645161290324
1981 4 25.766666666666666
1981 5 28.241935483870968
1981 6 35.88333333333333
1981 7 33.08064516129032
1981 8 33.435483870967744
1981 9 31.05
1981 10 24.93548387096774
1981 11 22.716666666666665
1981 12 19.016129032258064
1982 1 15.096774193548388
1982 2 18.696428571428573
1982 3 22.161290322580644
1982 4 26.283333333333335
1982 5 28.080645161290324
1982 6 34.15
1982 7 33.645161290322584
1982 8 33.11290322580645
1982 9 31.333333333333332
1982 10 27.20967741935484
1982 11 18.133333333333333
1982 12 12.838709677419354
1983 1 15.403225806451612
1983 2 17.339285714285715
1983 3 18.177419354838708
1983 4 20.1
1983 5 29.43548387096774
1983 6 32.53333333333333
1983 7 34.483870967741936
1983 8 32.67741935483871
1983 9 31.533333333333335
1983 10 23.951612903225808
1983 11 18.266666666666666
1983 12 16.903225806451612
1984 1 15.14516129032258
1984 2 17.98
1984 3 22.838709677419356
1984 4 24.383333333333333
1984 5 32.91935483870968
1984 6 33.05
1984 7 33.17741935483871
1984 8 31.112903225806452
1984 9 30.916666666666668
1984 10 22.5
1984 11 18.383333333333333
1984 12 14.112903225806452
1985 1 11.096774193548388
1985 2 15.982142857142858
1985 3 21.306451612903224
1985 4 25.45
1985 5 29.903225806451612
1985 6 nan
1985 7 35.096774193548384
1985 8 33.354838709677416
1985 9 28.9
1985 10 23.806451612903224
1985 11 19.166666666666668
1985 12 16.413793103448278
1986 1 20.612903225806452
1986 2 20.071428571428573
1986 3 22.870967741935484
1986 4 27.85
1986 5 31.193548387096776
1986 6 33.233333333333334
1986 7 31.70967741935484
1986 8 32.53225806451613
1986 9 30.533333333333335
1986 10 24.387096774193548
1986 11 18.066666666666666
1986 12 14.17741935483871
1987 1 14.53225806451613
1987 2 15.785714285714286
1987 3 19.112903225806452
1987 4 24.895833333333332
1987 5 27.194444444444443
1987 6 34.388888888888886
1987 7 nan
1987 8 nan
1987 9 29.2
1987 10 28.548387096774192
1987 11 19.7
1987 12 14.887096774193548
1988 1 15.903225806451612
1988 2 19.413793103448278
1988 3 23.516129032258064
1988 4 23.866666666666667
1988 5 30.677419354838708
1988 6 35.36666666666667
1988 7 33.70967741935484
1988 8 31.483870967741936
1988 9 30.0
1988 10 26.596774193548388
1988 11 20.433333333333334
1988 12 16.0
1989 1 14.774193548387096
1989 2 19.0
1989 3 25.032258064516128
1989 4 29.666666666666668
1989 5 31.0
1989 6 36.2
1989 7 35.83870967741935
1989 8 32.516129032258064
1989 9 32.3
1989 10 27.06451612903226
1989 11 22.0
1989 12 16.677419354838708
1990 1 16.129032258064516
1990 2 16.214285714285715
1990 3 20.70967741935484
1990 4 26.233333333333334
1990 5 28.903225806451612
1990 6 37.56666666666667
1990 7 32.145161290322584
1990 8 30.193548387096776
1990 9 30.666666666666668
1990 10 27.06451612903226
1990 11 20.366666666666667
1990 12 14.35483870967742
1991 1 14.096774193548388
1991 2 17.964285714285715
1991 3 18.516129032258064
1991 4 25.4
1991 5 29.225806451612904
1991 6 33.016666666666666
1991 7 33.95161290322581
1991 8 32.41935483870968
1991 9 28.866666666666667
1991 10 28.677419354838708
1991 11 20.266666666666666
1991 12 14.064516129032258
1992 1 12.129032258064516
1992 2 16.155172413793103
1992 3 19.532258064516128
1992 4 26.033333333333335
1992 5 28.629032258064516
1992 6 34.4
1992 7 34.20967741935484
1992 8 32.12903225806452
1992 9 32.93333333333333
1992 10 28.596774193548388
1992 11 18.883333333333333
1992 12 14.516129032258064
1993 1 14.580645161290322
1993 2 16.160714285714285
1993 3 21.887096774193548
1993 4 26.45
1993 5 30.483870967741936
1993 6 35.43333333333333
1993 7 32.95161290322581
1993 8 32.17741935483871
1993 9 31.666666666666668
1993 10 26.774193548387096
1993 11 19.93103448275862
1993 12 16.451612903225808
1994 1 17.758064516129032
1994 2 17.642857142857142
1994 3 21.5
1994 4 26.25
1994 5 30.016129032258064
1994 6 38.45
1994 7 36.87096774193548
1994 8 35.33870967741935
1994 9 31.5
1994 10 25.85483870967742
1994 11 18.983333333333334
1994 12 14.35483870967742
1995 1 14.806451612903226
1995 2 19.571428571428573
1995 3 21.806451612903224
1995 4 24.133333333333333
1995 5 27.887096774193548
1995 6 34.266666666666666
1995 7 35.725806451612904
1995 8 34.70967741935484
1995 9 32.166666666666664
1995 10 29.580645161290324
1995 11 23.333333333333332
1995 12 18.016129032258064
1996 1 18.129032258064516
1996 2 20.862068965517242
1996 3 22.516129032258064
1996 4 27.833333333333332
1996 5 33.564516129032256
1996 6 36.65
1996 7 34.645161290322584
1996 8 32.66129032258065
1996 9 29.95
1996 10 26.93548387096774
1996 11 22.033333333333335
1996 12 19.129032258064516
1997 1 15.564516129032258
1997 2 17.517857142857142
1997 3 24.725806451612904
1997 4 24.55
1997 5 32.61290322580645
1997 6 34.983333333333334
1997 7 36.83870967741935
1997 8 33.903225806451616
1997 9 33.81666666666667
1997 10 27.096774193548388

1997 11 21.4
1997 12 12.080645161290322
1998 1 17.806451612903224
1998 2 14.767857142857142
1998 3 20.35483870967742
1998 4 22.15
1998 5 30.258064516129032
1998 6 35.6
1998 7 34.41935483870968
1998 8 34.41935483870968
1998 9 34.45
1998 10 26.305555555555557
1998 11 nan
1998 12 nan
2000 1 nan
2000 2 nan
2000 3 nan
2000 4 nan
2000 5 nan
2000 6 nan
2000 7 nan
2000 8 nan
2000 9 nan
2000 10 24.629032258064516
2000 11 17.566666666666666
2000 12 19.5
2001 1 14.435483870967742
2001 2 19.5
2001 3 23.032258064516128
2001 4 27.433333333333334
2001 5 33.903225806451616
2001 6 36.81666666666667
2001 7 33.87096774193548
2001 8 34.53225806451613
2001 9 34.72222222222222
2001 10 30.310344827586206
2001 11 22.766666666666666
2001 12 17.06451612903226
2002 1 nan
2002 2 20.107142857142858
2002 3 23.951612903225808
2002 4 29.233333333333334
2002 5 32.806451612903224
2002 6 39.0
2002 7 35.806451612903224
2002 8 34.016129032258064
2002 9 33.0
2002 10 26.43548387096774
2002 11 23.333333333333332
2002 12 16.5
2003 1 23.85483870967742
2003 2 19.767857142857142
2003 3 23.241935483870968
2003 4 26.383333333333333
2003 5 32.693548387096776
2003 6 36.36666666666667
2003 7 38.62903225806452
2003 8 35.43103448275862
2003 9 34.55
2003 10 31.451612903225808
2003 11 23.55
2003 12 20.5
2004 1 18.56451612903226
2004 2 19.482758620689655
2004 3 26.56451612903226
2004 4 25.233333333333334
2004 5 32.274193548387096
2004 6 35.85
2004 7 36.0
2004 8 34.206896551724135
2004 9 32.9
2004 10 28.032258064516128
2004 11 21.2
2004 12 18.879310344827587
2005 1 19.0
2005 2 18.160714285714285
2005 3 22.903225806451612
2005 4 27.433333333333334
2005 5 32.16129032258065
2005 6 35.93333333333333
2005 7 37.96774193548387
2005 8 33.87096774193548
2005 9 34.61666666666667
2005 10 31.774193548387096
2005 11 27.533333333333335
2005 12 24.322580645161292
2006 1 23.322580645161292
2006 2 24.232142857142858
2006 3 23.0
2006 4 28.9
2006 5 33.806451612903224
2006 6 38.05
2006 7 36.016129032258064
2006 8 32.193548387096776
2006 9 30.183333333333334
2006 10 28.258064516129032
2006 11 26.616666666666667
2006 12 20.580645161290324
2007 1 16.370967741935484
2007 2 22.160714285714285
2007 3 25.161290322580644
2007 4 26.716666666666665
2007 5 31.661290322580644
2007 6 37.233333333333334
2007 7 35.45161290322581
2007 8 34.37096774193548
2007 9 32.56666666666667
2007 10 33.193548387096776
2007 11 28.433333333333334
2007 12 19.2
2008 1 18.333333333333332
2008 2 22.96551724137931
2008 3 24.387096774193548
2008 4 28.9
2008 5 31.774193548387096
2008 6 38.36666666666667
2008 7 34.67741935483871
2008 8 34.806451612903224
2008 9 34.06666666666667
2008 10 32.903225806451616
2008 11 27.3
2008 12 20.63157894736842
2009 1 21.0
2009 2 22.892857142857142
2009 3 25.967741935483872
2009 4 26.304347826086957
2009 5 33.9
2009 6 34.333333333333336
2009 7 37.86363636363637
2009 8 36.27272727272727
2009 9 34.77272727272727
2009 10 27.571428571428573
2009 11 26.285714285714285
2009 12 18.083333333333332
2010 1 18.7
2010 2 18.3
2010 3 22.818181818181817
2010 4 27.0
2010 5 31.952380952380953
2010 6 38.26086956521739
2010 7 35.714285714285715
2010 8 35.73913043478261
2010 9 34.588235294117645
2010 10 29.9
2010 11 23.0
2010 12 22.5
2011 1 20.0
2011 2 20.36842105263158
2011 3 28.454545454545453
2011 4 30.57894736842105
2011 5 31.416666666666668
2011 6 38.57142857142857
2011 7 37.096774193548384
2011 8 nan
2011 9 nan
2011 10 nan
2011 11 nan
2011 12 nan

In [32]:
#sacamos el promedio de la precipitacion en los meses a traves de losm años
for j in lista:
    for i in range(1,13):
        waza=df.loc[(df['MES']== i) & (df['AÑO']== j),'PRECIP'].mean()
        print(j,i,waza)

1961 1 nan
1961 2 0.03571428571428571
1961 3 0.0
1961 4 0.0
1961 5 0.0
1961 6 0.4
1961 7 3.6129032258064515
1961 8 1.8225806451612903
1961 9 1.5333333333333334
1961 10 0.967741935483871
1961 11 0.6666666666666666
1961 12 1.1935483870967742
1962 1 1.2419354838709677
1962 2 0.03571428571428571
1962 3 0.5967741935483871
1962 4 0.13333333333333333
1962 5 0.0
1962 6 0.4666666666666667
1962 7 1.8709677419354838
1962 8 nan
1962 9 nan
1962 10 nan
1962 11 nan
1962 12 nan
1963 1 0.0
1963 2 nan
1963 3 nan
1963 4 nan
1963 5 nan
1963 6 nan
1963 7 nan
1963 8 nan
1963 9 3.048275862068966
1963 10 0.7741935483870968
1963 11 0.7833333333333333
1963 12 0.22580645161290322
1964 1 0.0
1964 2 0.05172413793103448
1964 3 0.25806451612903225
1964 4 0.13333333333333333
1964 5 0.0
1964 6 0.0
1964 7 4.758064516129032
1964 8 2.7419354838709675
1964 9 2.4
1964 10 0.0967741935483871
1964 11 0.06666666666666667
1964 12 0.0
1965 1 0.7741935483870968
1965 2 0.2857142857142857
1965 3 0.3548387096774194
1965 4 0.0
1965 5 0.25806451612903225
1965 6 0.38333333333333336
1965 7 3.774193548387097
1965 8 2.6129032258064515
1965 9 0.75
1965 10 0.0
1965 11 0.0
1965 12 2.935483870967742
1966 1 0.7741935483870968
1966 2 0.6785714285714286
1966 3 0.0
1966 4 0.2
1966 5 0.0
1966 6 0.26666666666666666
1966 7 4.935483870967742
1966 8 3.9612903225806453
1966 9 3.369999999999999
1966 10 0.04516129032258064
1966 11 0.18000000000000002
1966 12 0.03225806451612903
1967 1 0.0
1967 2 0.125
1967 3 0.0
1967 4 0.3
1967 5 0.41935483870967744
1967 6 0.5666666666666667
1967 7 3.5161290322580645
1967 8 4.435483870967742
1967 9 1.1166666666666667
1967 10 0.0
1967 11 1.0066666666666666
1967 12 3.8870967741935485
1968 1 0.3064516129032258
1968 2 0.9655172413793104
1968 3 0.8387096774193549
1968 4 0.31666666666666665
1968 5 0.0
1968 6 0.0
1968 7 3.5580645161290323
1968 8 2.3548387096774195
1968 9 0.5
1968 10 0.0
1968 11 0.7833333333333333
1968 12 0.3225806451612903
1969 1 0.41935483870967744
1969 2 0.2857142857142857
1969 3 0.0
1969 4 0.1
1969 5 0.532258064516129
1969 6 0.0
1969 7 3.4516129032258065
1969 8 2.2096774193548385
1969 9 1.1
1969 10 0.0
1969 11 0.1
1969 12 0.6290322580645161
1970 1 0.0967741935483871
1970 2 0.35714285714285715
1970 3 0.6290322580645161
1970 4 0.18333333333333332
1970 5 0.0
1970 6 0.0
1970 7 1.2419354838709677
1970 8 3.0161290322580645
1970 9 0.6666666666666666
1970 10 0.3870967741935484
1970 11 0.0
1970 12 0.2903225806451613
1971 1 0.0
1971 2 0.8571428571428571
1971 3 0.0
1971 4 0.1
1971 5 0.0
1971 6 0.23333333333333334
1971 7 3.4193548387096775
1971 8 3.3548387096774195
1971 9 0.6833333333333333
1971 10 0.9032258064516129
1971 11 0.36666666666666664
1971 12 1.6290322580645162
1972 1 0.0
1972 2 0.0
1972 3 0.0
1972 4 0.0
1972 5 0.20967741935483872
1972 6 0.75
1972 7 nan
1972 8 nan
1972 9 nan
1972 10 nan
1972 11 nan
1972 12 nan
1973 1 nan
1973 2 nan
1973 3 nan
1973 4 nan
1973 5 nan
1973 6 nan
1973 7 nan
1973 8 nan
1973 9 nan
1973 10 0.0
1973 11 0.35
1973 12 0.0
1974 1 0.5161290322580645
1974 2 0.0
1974 3 0.0
1974 4 0.0
1974 5 0.0
1974 6 0.26666666666666666
1974 7 3.7838709677419353
1974 8 2.1838709677419352
1974 9 1.3566666666666667
1974 10 1.461290322580645
1974 11 0.5433333333333333
1974 12 0.016129032258064516
1975 1 0.635483870967742
1975 2 0.0
1975 3 0.5709677419354838
1975 4 0.14
1975 5 0.0
1975 6 0.0
1975 7 3.193548387096774
1975 8 0.3290322580645161
1975 9 2.6
1975 10 0.2838709677419355
1975 11 1.51
1975 12 0.267741935483871
1976 1 0.14838709677419354
1976 2 0.6862068965517241
1976 3 0.03225806451612903
1976 4 1.1066666666666667
1976 5 0.45161290322580644
1976 6 0.5666666666666667
1976 7 1.6387096774193548
1976 8 0.6322580645161291
1976 9 2.58
1976 10 0.5612903225806452
1976 11 0.7133333333333333
1976 12 0.2161290322580645
1977 1 1.5516129032258066
1977 2 0.0
1977 3 0.16129032258064516
1977 4 0.05
1977 5 0.0
1977 6 0.67
1977 7 2.809677419354839
1977 8 2.5548387096774197
1977 9 2.186666666666667
1977 10 4.974193548387096
1977 11 0.33666666666666667
1977 12 0.6483870967741935
1978 1 0.8354838709677419
1978 2 1.5964285714285715
1978 3 1.1870967741935483
1978 4 0.0
1978 5 0.432258064516129
1978 6 0.7466666666666666
1978 7 1.9967741935483874
1978 8 2.316129032258064
1978 9 0.47000000000000003
1978 10 1.096774193548387
1978 11 1.4200000000000002
1978 12 2.436
1979 1 1.4709677419354836
1979 2 0.23928571428571432
1979 3 0.4387096774193549
1979 4 0.0
1979 5 0.1903225806451613
1979 6 0.33000000000000007
1979 7 2.148387096774193
1979 8 4.054838709677419
1979 9 0.24333333333333332
1979 10 0.0
1979 11 0.22666666666666666
1979 12 0.6064516129032258
1980 1 0.6096774193548387
1980 2 1.5896551724137935
1980 3 0.267741935483871
1980 4 0.08333333333333333
1980 5 0.0
1980 6 0.49666666666666665
1980 7 2.0129032258064523
1980 8 3.1032258064516136
1980 9 1.4633333333333334
1980 10 0.03225806451612903
1980 11 0.18000000000000002
1980 12 0.17419354838709677
1981 1 1.4516129032258063
1981 2 0.525
1981 3 0.6580645161290323
1981 4 0.6733333333333335
1981 5 0.2129032258064516
1981 6 2.5266666666666664
1981 7 2.203225806451613
1981 8 0.8516129032258064
1981 9 1.0433333333333332
1981 10 0.9258064516129032
1981 11 0.92
1981 12 0.03225806451612903
1982 1 0.6580645161290322
1982 2 0.10357142857142858
1982 3 0.3645161290322581
1982 4 0.02333333333333333
1982 5 0.4774193548387097
1982 6 0.23333333333333334
1982 7 2.9290322580645163
1982 8 2.0677419354838706
1982 9 1.3066666666666669
1982 10 0.0
1982 11 1.4566666666666668
1982 12 2.3
1983 1 0.8870967741935484
1983 2 1.432142857142857
1983 3 1.5290322580645166
1983 4 0.12333333333333334
1983 5 0.01935483870967742
1983 6 0.07
1983 7 4.796774193548388
1983 8 1.5548387096774197
1983 9 4.136666666666667
1983 10 2.396774193548387
1983 11 2.1
1983 12 0.5516129032258065
1984 1 0.7451612903225807
1984 2 0.0
1984 3 0.0
1984 4 0.19666666666666668
1984 5 0.0
1984 6 0.5666666666666667
1984 7 4.564516129032258
1984 8 6.248387096774193
1984 9 0.6833333333333333
1984 10 2.774193548387097
1984 11 0.23
1984 12 2.735483870967742
1985 1 1.2419354838709677
1985 2 0.9821428571428571
1985 3 0.24193548387096775
1985 4 0.8333333333333334
1985 5 0.0
1985 6 nan
1985 7 2.4193548387096775
1985 8 1.6903225806451612
1985 9 2.8333333333333335
1985 10 3.5258064516129033
1985 11 0.8333333333333334
1985 12 0.43103448275862066
1986 1 0.3548387096774194
1986 2 0.6785714285714286
1986 3 0.45161290322580644
1986 4 0.05
1986 5 0.0
1986 6 0.8666666666666667
1986 7 4.380645161290323
1986 8 2.6129032258064515
1986 9 0.85
1986 10 0.45161290322580644
1986 11 1.3833333333333333
1986 12 2.5677419354838706
1987 1 0.0
1987 2 1.3571428571428572
1987 3 0.30000000000000004
1987 4 0.21600000000000003
1987 5 0.6842105263157895
1987 6 1.3518518518518519
1987 7 nan
1987 8 nan
1987 9 1.2966666666666666
1987 10 0.18387096774193548
1987 11 0.06666666666666667
1987 12 1.6129032258064515
1988 1 0.45161290322580644
1988 2 0.08620689655172414
1988 3 0.20967741935483872
1988 4 1.3933333333333333
1988 5 0.016129032258064516
1988 6 0.0
1988 7 2.2129032258064516
1988 8 4.580645161290323
1988 9 1.6666666666666667
1988 10 2.203225806451613
1988 11 0.12666666666666665
1988 12 2.740740740740741
1989 1 0.6903225806451613
1989 2 0.2571428571428572
1989 3 0.45161290322580644
1989 4 0.7166666666666667
1989 5 0.20967741935483872
1989 6 0.0
1989 7 2.5
1989 8 3.3870967741935485
1989 9 0.22666666666666666
1989 10 0.7258064516129032
1989 11 0.0
1989 12 0.1870967741935484
1990 1 0.20967741935483872
1990 2 0.6071428571428571
1990 3 0.12903225806451613
1990 4 0.2833333333333333
1990 5 0.1935483870967742
1990 6 0.38333333333333336
1990 7 5.387096774193548
1990 8 2.0161290322580645
1990 9 1.5666666666666667
1990 10 0.8709677419354839
1990 11 1.35
1990 12 0.9032258064516129
1991 1 1.1129032258064515
1991 2 0.7857142857142857
1991 3 0.14516129032258066
1991 4 0.06666666666666667
1991 5 0.0
1991 6 0.6633333333333333
1991 7 0.5483870967741935
1991 8 4.887096774193548
1991 9 2.7
1991 10 0.12903225806451613
1991 11 0.26666666666666666
1991 12 3.370967741935484
1992 1 1.096774193548387
1992 2 0.43103448275862066
1992 3 1.1774193548387097
1992 4 0.06666666666666667
1992 5 1.8387096774193548
1992 6 0.2833333333333333
1992 7 2.629032258064516
1992 8 2.4193548387096775
1992 9 0.5833333333333334
1992 10 0.3870967741935484
1992 11 0.36666666666666664
1992 12 1.0290322580645161
1993 1 2.903225806451613
1993 2 0.6428571428571429
1993 3 0.22580645161290322
1993 4 0.0
1993 5 0.7903225806451613
1993 6 0.31666666666666665
1993 7 2.5
1993 8 2.629032258064516
1993 9 0.23333333333333334
1993 10 0.1935483870967742
1993 11 0.6833333333333333
1993 12 0.17096774193548386
1994 1 0.06451612903225806
1994 2 0.5714285714285714
1994 3 0.27419354838709675
1994 4 0.0
1994 5 0.14516129032258066
1994 6 0.48333333333333334
1994 7 1.2903225806451613
1994 8 2.2806451612903227
1994 9 2.7
1994 10 0.06451612903225806
1994 11 2.533333333333333
1994 12 3.1322580645161286
1995 1 0.27419354838709675
1995 2 1.4285714285714286
1995 3 0.11290322580645161
1995 4 0.1
1995 5 0.0
1995 6 0.0
1995 7 2.3225806451612905
1995 8 2.5161290322580645
1995 9 1.1166666666666667
1995 10 0.25806451612903225
1995 11 0.43333333333333335
1995 12 0.27419354838709675
1996 1 0.0
1996 2 0.13793103448275862
1996 3 0.012903225806451613
1996 4 0.0
1996 5 0.0
1996 6 1.8666666666666667
1996 7 3.6129032258064515
1996 8 1.9193548387096775
1996 9 2.6333333333333333
1996 10 0.2903225806451613
1996 11 0.11666666666666667
1996 12 0.0
1997 1 0.20967741935483872
1997 2 0.8035714285714286
1997 3 0.11290322580645161
1997 4 0.2833333333333333
1997 5 0.46774193548387094
1997 6 0.15
1997 7 1.2096774193548387
1997 8 2.0806451612903225
1997 9 0.8833333333333333
1997 10 0.1935483870967742
1997 11 1.2166666666666666
1997 12 2.129032258064516
1998 1 0.016129032258064516
1998 2 1.2678571428571428
1998 3 0.867741935483871
1998 4 0.15666666666666668
1998 5 0.0
1998 6 0.05
1998 7 4.15483870967742
1998 8 2.064516129032258
1998 9 0.11904761904761904
1998 10 0.2777777777777778
1998 11 nan
1998 12 nan
2000 1 nan
2000 2 nan
2000 3 nan
2000 4 nan
2000 5 nan
2000 6 nan
2000 7 nan
2000 8 nan
2000 9 nan
2000 10 3.9838709677419355
2000 11 1.0666666666666667
2000 12 0.0
2001 1 0.8387096774193549
2001 2 0.03571428571428571
2001 3 0.12903225806451613
2001 4 0.43333333333333335
2001 5 0.1935483870967742
2001 6 0.6833333333333333
2001 7 4.9645161290322575
2001 8 1.2741935483870968
2001 9 0.33
2001 10 0.532258064516129
2001 11 0.31
2001 12 0.3870967741935484
2002 1 nan
2002 2 1.282142857142857
2002 3 0.0
2002 4 0.0
2002 5 0.0
2002 6 0.0
2002 7 2.6322580645161286
2002 8 2.074193548387097
2002 9 2.55
2002 10 0.0935483870967742
2002 11 0.15666666666666668

2002 12 0.7516129032258064
2003 1 0.0
2003 2 0.8928571428571429
2003 3 0.22580645161290322
2003 4 0.0
2003 5 0.0
2003 6 0.016666666666666666
2003 7 0.8387096774193549
2003 8 1.6870967741935483
2003 9 0.6333333333333333
2003 10 0.532258064516129
2003 11 0.8833333333333333
2003 12 0.47096774193548385
2004 1 0.5741935483870968
2004 2 0.45862068965517244
2004 3 0.8483870967741935
2004 4 0.8
2004 5 0.0
2004 6 0.15
2004 7 0.7333333333333333
2004 8 2.106896551724138
2004 9 1.5833333333333333
2004 10 0.5806451612903226
2004 11 0.65
2004 12 0.4838709677419355
2005 1 2.3774193548387097
2005 2 1.7142857142857142
2005 3 0.1935483870967742
2005 4 0.16666666666666666
2005 5 0.2903225806451613
2005 6 0.0
2005 7 1.0161290322580645
2005 8 3.2903225806451615
2005 9 0.11666666666666667
2005 10 0.12903225806451613
2005 11 0.2
2005 12 0.04838709677419355
2006 1 0.14516129032258066
2006 2 0.10714285714285714
2006 3 0.0
2006 4 0.0
2006 5 0.0
2006 6 0.1
2006 7 4.274193548387097
2006 8 3.596774193548387
2006 9 1.8166666666666667
2006 10 0.9354838709677419
2006 11 0.0
2006 12 0.24193548387096775
2007 1 1.103225806451613
2007 2 0.0
2007 3 0.9516129032258065
2007 4 0.08333333333333333
2007 5 0.04838709677419355
2007 6 0.7
2007 7 3.725806451612903
2007 8 5.17741935483871
2007 9 1.1166666666666667
2007 10 0.1935483870967742
2007 11 0.6033333333333334
2007 12 0.3387096774193548
2008 1 0.05357142857142857
2008 2 0.06896551724137931
2008 3 0.0
2008 4 0.0
2008 5 0.03225806451612903
2008 6 0.15
2008 7 2.903225806451613
2008 8 3.032258064516129
2008 9 0.4
2008 10 0.0
2008 11 0.4
2008 12 0.1935483870967742
2009 1 0.08064516129032258
2009 2 0.21428571428571427
2009 3 0.6774193548387096
2009 4 0.0
2009 5 0.06451612903225806
2009 6 0.55
2009 7 2.064516129032258
2009 8 1.3387096774193548
2009 9 0.45
2009 10 0.5
2009 11 0.36666666666666664
2009 12 0.01935483870967742
2010 1 1.9193548387096775
2010 2 3.25
2010 3 0.06451612903225806
2010 4 0.23333333333333334
2010 5 0.0
2010 6 0.1
2010 7 3.7580645161290325
2010 8 1.9516129032258065
2010 9 0.85
2010 10 0.14516129032258066
2010 11 1.1733333333333333
2010 12 0.0
2011 1 0.0
2011 2 0.0
2011 3 0.0
2011 4 0.0
2011 5 0.0
2011 6 0.08333333333333333
2011 7 4.516129032258065
2011 8 nan
2011 9 nan
2011 10 nan
2011 11 nan
2011 12 nan